name: https://ch1pepf0000a34c.mail.protection.outlook.com

on:https://photos.app.goo.gl/aSRop8VCz1TpNNHT6
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
